// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/vehicle/vehicle.proto

package vehiclepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	OwnerName          string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year               int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vehicle) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *Vehicle) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type CreateVehicleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RegistrationNumber string                 `protobuf:"bytes,1,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	OwnerName          string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Model              string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year               int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVehicleRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *CreateVehicleRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *CreateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{2}
}

func (x *GetVehicleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateVehicleRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistrationNumber string                 `protobuf:"bytes,2,opt,name=registration_number,json=registrationNumber,proto3" json:"registration_number,omitempty"`
	OwnerName          string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year               int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateVehicleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateVehicleRequest) GetRegistrationNumber() string {
	if x != nil {
		return x.RegistrationNumber
	}
	return ""
}

func (x *UpdateVehicleRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVehicleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleResponse) Reset() {
	*x = VehicleResponse{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleResponse) ProtoMessage() {}

func (x *VehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleResponse.ProtoReflect.Descriptor instead.
func (*VehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{5}
}

func (x *VehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type DeleteVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleResponse) Reset() {
	*x = DeleteVehicleResponse{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleResponse) ProtoMessage() {}

func (x *DeleteVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleResponse.ProtoReflect.Descriptor instead.
func (*DeleteVehicleResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVehicleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{7}
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vehicle_vehicle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_proto_vehicle_vehicle_proto_rawDescGZIP(), []int{8}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

var File_proto_vehicle_vehicle_proto protoreflect.FileDescriptor

const file_proto_vehicle_vehicle_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/vehicle/vehicle.proto\x12\avehicle\"\x93\x01\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\"\x90\x01\n" +
	"\x14CreateVehicleRequest\x12/\n" +
	"\x13registration_number\x18\x01 \x01(\tR\x12registrationNumber\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\"#\n" +
	"\x11GetVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xa0\x01\n" +
	"\x14UpdateVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12/\n" +
	"\x13registration_number\x18\x02 \x01(\tR\x12registrationNumber\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\"&\n" +
	"\x14DeleteVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"=\n" +
	"\x0fVehicleResponse\x12*\n" +
	"\avehicle\x18\x01 \x01(\v2\x10.vehicle.VehicleR\avehicle\"1\n" +
	"\x15DeleteVehicleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x15\n" +
	"\x13ListVehiclesRequest\"D\n" +
	"\x14ListVehiclesResponse\x12,\n" +
	"\bvehicles\x18\x01 \x03(\v2\x10.vehicle.VehicleR\bvehicles2\x85\x03\n" +
	"\x0eVehicleService\x12H\n" +
	"\rCreateVehicle\x12\x1d.vehicle.CreateVehicleRequest\x1a\x18.vehicle.VehicleResponse\x12B\n" +
	"\n" +
	"GetVehicle\x12\x1a.vehicle.GetVehicleRequest\x1a\x18.vehicle.VehicleResponse\x12H\n" +
	"\rUpdateVehicle\x12\x1d.vehicle.UpdateVehicleRequest\x1a\x18.vehicle.VehicleResponse\x12N\n" +
	"\rDeleteVehicle\x12\x1d.vehicle.DeleteVehicleRequest\x1a\x1e.vehicle.DeleteVehicleResponse\x12K\n" +
	"\fListVehicles\x12\x1c.vehicle.ListVehiclesRequest\x1a\x1d.vehicle.ListVehiclesResponseB6Z4vehicle-repair-microservices/proto/vehicle;vehiclepbb\x06proto3"

var (
	file_proto_vehicle_vehicle_proto_rawDescOnce sync.Once
	file_proto_vehicle_vehicle_proto_rawDescData []byte
)

func file_proto_vehicle_vehicle_proto_rawDescGZIP() []byte {
	file_proto_vehicle_vehicle_proto_rawDescOnce.Do(func() {
		file_proto_vehicle_vehicle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vehicle_vehicle_proto_rawDesc), len(file_proto_vehicle_vehicle_proto_rawDesc)))
	})
	return file_proto_vehicle_vehicle_proto_rawDescData
}

var file_proto_vehicle_vehicle_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vehicle_vehicle_proto_goTypes = []any{
	(*Vehicle)(nil),               // 0: vehicle.Vehicle
	(*CreateVehicleRequest)(nil),  // 1: vehicle.CreateVehicleRequest
	(*GetVehicleRequest)(nil),     // 2: vehicle.GetVehicleRequest
	(*UpdateVehicleRequest)(nil),  // 3: vehicle.UpdateVehicleRequest
	(*DeleteVehicleRequest)(nil),  // 4: vehicle.DeleteVehicleRequest
	(*VehicleResponse)(nil),       // 5: vehicle.VehicleResponse
	(*DeleteVehicleResponse)(nil), // 6: vehicle.DeleteVehicleResponse
	(*ListVehiclesRequest)(nil),   // 7: vehicle.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),  // 8: vehicle.ListVehiclesResponse
}
var file_proto_vehicle_vehicle_proto_depIdxs = []int32{
	0, // 0: vehicle.VehicleResponse.vehicle:type_name -> vehicle.Vehicle
	0, // 1: vehicle.ListVehiclesResponse.vehicles:type_name -> vehicle.Vehicle
	1, // 2: vehicle.VehicleService.CreateVehicle:input_type -> vehicle.CreateVehicleRequest
	2, // 3: vehicle.VehicleService.GetVehicle:input_type -> vehicle.GetVehicleRequest
	3, // 4: vehicle.VehicleService.UpdateVehicle:input_type -> vehicle.UpdateVehicleRequest
	4, // 5: vehicle.VehicleService.DeleteVehicle:input_type -> vehicle.DeleteVehicleRequest
	7, // 6: vehicle.VehicleService.ListVehicles:input_type -> vehicle.ListVehiclesRequest
	5, // 7: vehicle.VehicleService.CreateVehicle:output_type -> vehicle.VehicleResponse
	5, // 8: vehicle.VehicleService.GetVehicle:output_type -> vehicle.VehicleResponse
	5, // 9: vehicle.VehicleService.UpdateVehicle:output_type -> vehicle.VehicleResponse
	6, // 10: vehicle.VehicleService.DeleteVehicle:output_type -> vehicle.DeleteVehicleResponse
	8, // 11: vehicle.VehicleService.ListVehicles:output_type -> vehicle.ListVehiclesResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vehicle_vehicle_proto_init() }
func file_proto_vehicle_vehicle_proto_init() {
	if File_proto_vehicle_vehicle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vehicle_vehicle_proto_rawDesc), len(file_proto_vehicle_vehicle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vehicle_vehicle_proto_goTypes,
		DependencyIndexes: file_proto_vehicle_vehicle_proto_depIdxs,
		MessageInfos:      file_proto_vehicle_vehicle_proto_msgTypes,
	}.Build()
	File_proto_vehicle_vehicle_proto = out.File
	file_proto_vehicle_vehicle_proto_goTypes = nil
	file_proto_vehicle_vehicle_proto_depIdxs = nil
}
